### ISSUE TITLE
Yolov1的代码存在bug

### ISSUE THREAD

**Issue by eeyrw** [yjh0410/PyTorch_YOLO-Family#1]
这句：
https://github.com/yjh0410/PyTorch_YOLO-Family/blob/55a331a654ddbbd8e8449403ab452a9b61ceabe0/models/yolov1.py#L36
Yolov1不用anchor机制，这里运行的时候会出错。

**Comment by yjh0410** [comment]
@eeyrw 抱歉，前段时间重构代码的时候遗留下来的bug，现在已经修改了。非常感谢！
