### ISSUE TITLE
Using different dataset

### ISSUE THREAD

**Issue by kulkarnikeerti** [yjh0410/PyTorch_YOLO-Family#11]
Hi @yjh0410 

If I would want to use a different dataset instead of `COCO` and `VOC`, I would have to change the data pre-processing and also the data loader right? Do I have to keep anything else in mind? Or what exactly I should change?  Or can I just use another dataset (ex: `Mapillary`) directly?

**Comment by yjh0410** [comment]
@kulkarnikeerti 
If you want to use other dataset, you need to write a new dataset file for the new dataset. Please refer to `voc.py` for the format of the file content. As for other data pre-processing like data augmentation and data loader, you don't need to make any changes, just make sure the dataset file format is appropriate..

**Comment by kulkarnikeerti** [comment]
@yjh0410 
Okay, thanks a lot.
