### ISSUE TITLE
Anchor size selection?

### ISSUE THREAD

**Issue by kulkarnikeerti** [yjh0410/PyTorch_YOLO-Family#21]
Hi @yjh0410 @HIT-k544,

I am here gain with one more question? How do you select the values for this anchor size? Do these values differ depending on the dataset?

https://github.com/yjh0410/PyTorch_YOLO-Family/blob/e01ca7a0ce1d26778b19ec54be57d6d123fca9ab/config/yolo_config.py#L196

**Comment by yjh0410** [comment]
@kulkarnikeerti 
In `PyTorch_YOLO-Family`， the anchor size is copied from the official YOLOv3. You can also obtain the new anchor sizes by runing the `utils/kmeans_anchor.py` file.

**Comment by kulkarnikeerti** [comment]
@yjh0410 Thanks for taking your time and responding to my query.
