### ISSUE TITLE
What's the difference between "--conf_thresh" and "--nms_thresh" in this repo?

### ISSUE THREAD

**Issue by Met4physics** [yjh0410/PyTorch_YOLO-Family#24]
Both of thes two args have the same help text: 'NMS threshold'. So which one is the real 'NMS threshold'?

**Comment by yjh0410** [comment]
Sorry for my oversight. conf_thresh is the threshold used to filter background predictions, while nms_thresh is the threshold used in NMS to filter redundant detections of the same target.
