### ISSUE TITLE
FPS of YOLO_nano

### ISSUE THREAD

**Issue by kulkarnikeerti** [yjh0410/PyTorch_YOLO-Family#5]
Hi,

@yjh0410 Thanks for the great repo. I would like to know how to measure the FPS of the given model. Is there any article which you recommend to follow for the same? or can I get it from the existing repo with some modification?

Thanks in advance.

**Comment by yjh0410** [comment]
@kulkarnikeerti 
You can check 'benchmark.py' file, which is used to compute FPS of my YOLO models.

**Comment by kulkarnikeerti** [comment]
@yjh0410 Thanks, got it!
