### ISSUE TITLE
Evaluation on COCO-test-dev

### ISSUE THREAD

**Issue by kulkarnikeerti** [yjh0410/PyTorch_YOLO-Family#6]
Hi,

I am trying to test the `yolo_nano` model with `test2017` set. I have already downloaded the `test2017` dataset locally. And I tried the exact command mentioned in the `readme` file, that is 

`python eval.py -d coco-test \
               --cuda \
               -m yolov_nano \
               --weight path/to/weight \
               --img_size 640 \
                --root path/to/dataset/`

And the readme file says, this generates the `.json` file. However, unfortunately I end up with the error `FileNotFoundError: [Errno 2] No such file or directory: '/data/COCO/annotations/image_info_test-dev2017.json'`. This is understandable because there is no such file. 

@yjh0410 Did I miss something here? How do I test the model on test dataset?

Thanks!

**Comment by yjh0410** [comment]
@kulkarnikeerti 
You can download it from here:
[ttps://github.com/yjh0410/PyTorch_YOLO-Family/releases/download/yolo-weight/image_info_test-dev2017.json](url)
https://github.com/yjh0410/PyTorch_YOLO-Family/releases/download/yolo-weight/image_info_test-dev2017.json

You might also need this, if you want to evaluate the model on COCO2017 test(not test-dev):
[https://github.com/yjh0410/PyTorch_YOLO-Family/releases/download/yolo-weight/image_info_test2017.json](url)

**Comment by yjh0410** [comment]
@kulkarnikeerti 

You can download it from here:
[https://github.com/yjh0410/PyTorch_YOLO-Family/releases/download/yolo-weight/image_info_test-dev2017.json](url)


You might also need this, if you want to evaluate the model on COCO2017 test(not test-dev):
[https://github.com/yjh0410/PyTorch_YOLO-Family/releases/download/yolo-weight/image_info_test2017.json](url)

**Comment by kulkarnikeerti** [comment]
@yjh0410 Thanks for the links. But I guess they are broken. I don't find anything there. I don't see any `releases` folder in the repo. Below is the result with the link.

![image](https://user-images.githubusercontent.com/12002873/158957964-b2fecfbc-828c-4502-8d9e-69522a4f7832.png)

**Comment by yjh0410** [comment]
@kulkarnikeerti 
Please try to download from here:

[github](https://github.com/yjh0410/PyTorch_YOLO-Family/releases/download/yolo-weight/image_info_test-dev2017.json)

[gitjub](https://github.com/yjh0410/PyTorch_YOLO-Family/releases/download/yolo-weight/image_info_test2017.json)

**Comment by kulkarnikeerti** [comment]
@yjh0410 Thank you very much.

Just one last clarification: the results of `YOLO_Nano` in the table contains three different rows. `YOLO-Nano-320`, `YOLO-Nano-416`, `YOLO-Nano-512`. 

what does these numbers `320`, `416`, `512` in the name indicate? Are these the input image size?

**Comment by yjh0410** [comment]
@kulkarnikeerti 
Yes. For example, `320` means that the input image is resized to shape 320x320.

**Comment by kulkarnikeerti** [comment]
Okay. Thanks a lot again @yjh0410
