### ISSUE TITLE
Input image size as 1920 x 1080

### ISSUE THREAD

**Issue by kulkarnikeerti** [yjh0410/PyTorch_YOLO-Family#8]
Hi @yjh0410, thanks for the great repo and quick answer to the questions.

I would like to use the input image size as `1920 x 1080` instead of square image.
1. Is that possible to use this size with this yolo_nano model?
2. If yes, what are things I should consider changing in the model to work with this size?

Thanks a lot in advance.

**Comment by yjh0410** [comment]
@kulkarnikeerti 
If you want to try 1920 × 1080, you need to modify the code of resize operation. 

In my code, the longer size of input image is resized to the 640 or other size, and the shorter size is resized according to the original aspect ratio. After the resize operation, the aspect ratio is kept. For example, the origin size is 1280 x 640. After resize operation, it becomes 640 x 320. Then,  this image is padded with zero to 640 x 640 size. 

In all my code, I default the input image to be a square, so the code that requires the image length and width defaults to the length equal to the width, you may need to modify this.

However, such large size might be not friendly to YOLO-Nano. It might need very long time to make inference, so the real-time detection can not be kept. You would better to design carefully.

**Comment by kulkarnikeerti** [comment]
@yjh0410 Thanks a lot. I will give it a try.
